name: skr_1p4t

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths-ignore:
    - src/configs/V1*Archim*
    - src/configs/V1*Rambo*
    - src/configs/V1*Ramps*
    - src/configs/V1*SkrPro*
    - src/configs/V1*Skr1p3*
    - src/configs/V1*Skr1p4*
    - '**/*.md'
  release:
    types:
      - published

jobs:
  build:

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}
      V1_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

    name: ${{ matrix.machine }}-${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch: ${{ fromJson(
          github.event_name == 'schedule' && '["bugfix-2.0.x"]' ||
          github.event_name == 'pull_request' && '["bugfix-2.0.x", "2.0.7.2"]' ||
          '["2.0.7.2"]') }}
        machine:
        - V1CNC_Skr1p4t_2209
        - V1CNC_Skr1p4t_Dual_2209
        - V1CNC_Skr1p4t_DualLR_2209

    steps:

    # First, cancel unfinished jobs.
    - uses: technote-space/auto-cancel-redundant-job@v1

    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Check out MarlinBuilder
      uses: actions/checkout@v2

    - name: Check out MarlinFirmware
      uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        ref: ${{ matrix.branch }}
        path: Marlin
        clean: true
        fetch-depth: 1

    - name: Display the path
      run: |
        echo $PATH
        pwd
        ls -lisah
        ls Marlin/
        ls Marlin/src/
        ls Marlin/src/pins/
        ls Marlin/src/pins/lpc1768/
      shell: bash
            
    - name: Change pins file for skr1p4 and 1pk4t
      run: cp skr1p4_pins.h Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_4.h

    - name: Configure
      run: |
        src/core/config-for-machine ${{ matrix.machine }}

    - name: Build
      run: |
        src/core/build-for-machine

    - name: Zip up Marlin
      run: |
        src/core/zip-marlin

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.machine }}-${{ matrix.branch }}
        path: |
          firmware*
          Marlin_*.zip

    - name: Upload Marlin-${{ matrix.machine }}-${{ matrix.branch }}-src.zip to release
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Marlin-Release.zip
        asset_name: ${{ matrix.machine }}-${{ matrix.branch }}-src.zip
        asset_content_type: application/zip
